node {
    stage('Checkout') {
        checkout scm
    }

    stage('Build') {
        sh 'npm run build'
    }

    stage('build docker image') {
        sh 'docker build -t nodeapp .'
    } 
    
}