node {
    stage('Checkout') {
        checkout scm
    }
    stage('Install dependencies') {
        sh 'npm install'
    }
    stage('Build') {
        sh 'npm run build'
    }
    stage('Test') {
        sh 'npm test'
    }
    stage('Deploy') {
        sh 'scp -r ./* ec2-user@18.206.177.107:/home/ec2-user/nodeapp'
    } 
    stage('Restart server') {
        sshagent(['ec2-user@18.206.177.107']) {
            sh 'sudo systemctl restart nodeapp.service'
        } 
    }
}