pipeline {
  agent { node { label 'jenkins_slave' } }
  stages {
    stage('Checkout') {
        checkout scm
    }
    stage('Install dependencies') {
        sh 'npm install'
    }
    stage('Build') {
        sh 'npm run build'
    }
    stage('Test') {
        sh 'npm test'
    } 
  }
}