---
- name: Configure Jenkins slave
  hosts: app
  become: yes
  vars:
    jenkins_user: jenkins
    jenkins_home: /home/{{ jenkins_user }}
  tasks:
    - name: Install Java
      yum:
        name: java-1.8.0-openjdk-devel
        state: present

    - name: Create Jenkins user
      user:
        name: "{{ jenkins_user }}"
        home: "{{ jenkins_home }}"
        shell: /bin/bash

    - name: Create .ssh directory for Jenkins user
      file:
        path: "{{ jenkins_home }}/.ssh"
        state: directory
        owner: "{{ jenkins_user }}"
        group: "{{ jenkins_user }}"
        mode: 0700

    - name: Copy private key for Jenkins user
      copy:
        src: ./ssh.pem
        dest: "{{ jenkins_home }}/.ssh/id_rsa"
        owner: "{{ jenkins_user }}"
        group: "{{ jenkins_user }}"
        mode: 0600

    - name: Add Jenkins user to sudoers
      lineinfile:
        path: /etc/sudoers
        state: present
        line: "{{ jenkins_user }} ALL=(ALL) NOPASSWD: ALL"
        validate: visudo -cf %s
