- name: Configure Jenkins slave
  hosts: app
  become: yes
  vars:
    jenkins_user: jenkins
    jenkins_home: /home/{{ jenkins_user }}
    public_key: "{{ lookup('file', './ssh.pub') }}"
  tasks:
    - name: Update all packages
      yum:
        name: "*"
        state: latest

    - name: Install Docker
      yum:
        name: docker
        state: present

    - name: Start and enable Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Install pip
      yum:
        name: python-pip
        state: present

    - name: Install Docker Python module
      pip:
        name: docker
        state: present

    - name: Install Java
      yum:
        name: java-11-amazon-corretto
        state: present

    - name: Install Jenkins slave required packages
      yum:
        name:
          - git
          - wget
        state: present

    - name: Create Jenkins user
      user:
        name: "{{ jenkins_user }}"
        home: "{{ jenkins_home }}"
        shell: /bin/bash
        state: present

    - name: Add public key to Jenkins user
      authorized_key:
        user: "{{ jenkins_user }}"
        key: "{{ public_key }}"
        state: present

    - name: Add public key to root user
      authorized_key:
        user: "root"
        key: "{{ public_key }}"
        state: present

    - name: Create Jenkins workspace directory
      file:
        path: "{{ jenkins_home }}/workspace"
        state: directory
        owner: "{{ jenkins_user }}"
        group: "{{ jenkins_user }}"
        mode: 0755

    - name: Install Jenkins slave
      become: true
      shell: curl -L https://updates.jenkins.io/download/war/2.263/slave.jar -o slave.jar && chmod 755 slave.jar

    - name: Start Jenkins slave
      become: true
      shell: nohup java -jar slave.jar >/dev/null 2>&1 &